var centro = {
          "type": "FeatureCollection",
          "features": [
       { "geometry": { "type": "Point", "coordinates": [ -60.647812, -32.940932] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Administracion Provincial de Impuestos (A.P.I)" }, "id": 116005},
       { "geometry": { "type": "Point", "coordinates": [ -60.659221, -32.942786] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc.Tecnica Nº 625" }, "id": 70393},
       { "geometry": { "type": "Point", "coordinates": [ -60.647484, -32.943792] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Colegio Adoratrices" }, "id": 67949},
       { "geometry": { "type": "Point", "coordinates": [ -60.652807, -32.95494] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: La Gallega supermercados" }, "id": 84659},
       { "geometry": { "type": "Point", "coordinates": [ -60.649928, -32.967509] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Impack s.a" }, "id": 103225},
       { "geometry": { "type": "Point", "coordinates": [ -60.628423, -32.957411] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Laboratorio cibic S.A." }, "id": 103237},
       { "geometry": { "type": "Point", "coordinates": [ -60.628533, -32.959893] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Laboratorio Cibic s.a" }, "id": 103239},
       { "geometry": { "type": "Point", "coordinates": [ -60.644475, -32.938133] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Edificio Irupe" }, "id": 116003},
       { "geometry": { "type": "Point", "coordinates": [ -60.663105, -32.961398] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: I.C.E.F Instituto Superior de Educacion Fisica" }, "id": 116002},
       { "geometry": { "type": "Point", "coordinates": [ -60.641324, -32.9387] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Aguas santafesinas S.A." }, "id": 108971},
       { "geometry": { "type": "Point", "coordinates": [ -60.655204, -32.950129] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Trasera" }, "id": 119813},
       { "geometry": { "type": "Point", "coordinates": [ -60.633792, -32.970649] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Jardiin de infantes Nº 51 Constancio C. Vigil" }, "id": 83546},
       { "geometry": { "type": "Point", "coordinates": [ -60.648109, -32.946274] },
                "type": "Feature", "properties": { "popupContent": "Queens centro" }, "id": 127314},
       { "geometry": { "type": "Point", "coordinates": [ -60.630964, -32.952229] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio S.O.M.U Sindicato de Obreros Mariitimos Unidos" }, "id": 83713},
       { "geometry": { "type": "Point", "coordinates": [ -60.630637, -32.96644] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio" }, "id": 83716},
       { "geometry": { "type": "Point", "coordinates": [ -60.634556, -32.947052] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Facultad de Derecho" }, "id": 83452},
       { "geometry": { "type": "Point", "coordinates": [ -60.641268, -32.93665] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: CMD Centro Antonio Berni" }, "id": 83450},
       { "geometry": { "type": "Point", "coordinates": [ -60.644362, -32.956447] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Centro Educativo Latinoamericano" }, "id": 83397},
       { "geometry": { "type": "Point", "coordinates": [ -60.625567, -32.968262] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  huerta Siempre Verde" }, "id": 83399},
       { "geometry": { "type": "Point", "coordinates": [ -60.64805, -32.936255] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 54 Manuel Belgrano" }, "id": 83401},
       { "geometry": { "type": "Point", "coordinates": [ -60.634431, -32.95356] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Mariia Bicceci Nº 8038" }, "id": 83402},
       { "geometry": { "type": "Point", "coordinates": [ -60.63669, -32.945917] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Banco Municipal" }, "id": 83404},
       { "geometry": { "type": "Point", "coordinates": [ -60.639359, -32.944646] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Oficina Grupo Oneto" }, "id": 83405},
       { "geometry": { "type": "Point", "coordinates": [ -60.656642, -32.971377] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio Gaboto" }, "id": 83407},
       { "geometry": { "type": "Point", "coordinates": [ -60.631321, -32.945694] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Secretariia de Produccion y Desarrollo Local" }, "id": 83410},
       { "geometry": { "type": "Point", "coordinates": [ -60.624233, -32.959017] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Planetario" }, "id": 83411},
       { "geometry": { "type": "Point", "coordinates": [ -60.65125, -32.946199] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Instituto de la Mujer" }, "id": 83413},
       { "geometry": { "type": "Point", "coordinates": [ -60.639233, -32.941539] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio San Bartolome" }, "id": 83414},
       { "geometry": { "type": "Point", "coordinates": [ -60.654874, -32.9381] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  OCA - Organizacion Coordinadora Argentina" }, "id": 83417},
       { "geometry": { "type": "Point", "coordinates": [ -60.629947, -32.948217] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Concejo Municipal" }, "id": 83423},
       { "geometry": { "type": "Point", "coordinates": [ -60.65125, -32.946199] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  CEMAR" }, "id": 83424},
       { "geometry": { "type": "Point", "coordinates": [ -60.637449, -32.938593] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Parque España" }, "id": 83425},
       { "geometry": { "type": "Point", "coordinates": [ -60.624967, -32.952484] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Club Nautico Rosario" }, "id": 83427},
       { "geometry": { "type": "Point", "coordinates": [ -60.635325, -32.948026] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Grupo Printing" }, "id": 83454},
       { "geometry": { "type": "Point", "coordinates": [ -60.640209, -32.948155] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: La Comedia Teatro Municipal" }, "id": 83466},
       { "geometry": { "type": "Point", "coordinates": [ -60.634353, -32.94143] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Galpon Centro de la Juventud" }, "id": 83460},
       { "geometry": { "type": "Point", "coordinates": [ -60.655339, -32.962481] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Dir. Gral. de Parques y Paseo" }, "id": 83461},
       { "geometry": { "type": "Point", "coordinates": [ -60.656715, -32.930826] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Sec. Cultura y Educacion" }, "id": 83456},
       { "geometry": { "type": "Point", "coordinates": [ -60.63244, -32.94696] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Palacio Municipal" }, "id": 83459},
       { "geometry": { "type": "Point", "coordinates": [ -60.640314, -32.937234] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: La Isla de los Inventos" }, "id": 83457},
       { "geometry": { "type": "Point", "coordinates": [ -60.631591, -32.946965] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Club Sportivo Servando Bayo" }, "id": 83472},
       { "geometry": { "type": "Point", "coordinates": [ -60.63852, -32.945109] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Club Saladillo" }, "id": 83487},
       { "geometry": { "type": "Point", "coordinates": [ -60.631995, -32.951403] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Salud El Gaucho" }, "id": 83496},
       { "geometry": { "type": "Point", "coordinates": [ -60.641969, -32.943492] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Sancor Seguros. SA." }, "id": 83431},
       { "geometry": { "type": "Point", "coordinates": [ -60.636688, -32.962599] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  IRT Medicina Laboral" }, "id": 83434},
       { "geometry": { "type": "Point", "coordinates": [ -60.634346, -32.953219] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio de Farmaceuticos" }, "id": 83435},
       { "geometry": { "type": "Point", "coordinates": [ -60.651707, -32.943848] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Secundaria Normal 2 J. M. Gutierrez" }, "id": 83436},
       { "geometry": { "type": "Point", "coordinates": [ -60.655688, -32.933412] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Blue Connect (Call Center) Point" }, "id": 83437},
       { "geometry": { "type": "Point", "coordinates": [ -60.657446, -32.953917] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio Museion Construcciones Fundar" }, "id": 83438},
       { "geometry": { "type": "Point", "coordinates": [ -60.636118, -32.95792] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio" }, "id": 83440},
       { "geometry": { "type": "Point", "coordinates": [ -60.640164, -32.947993] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  General Motors" }, "id": 83441},
       { "geometry": { "type": "Point", "coordinates": [ -60.653859, -32.947085] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Sancor Seguros Centro Medico Laboral" }, "id": 83442},
       { "geometry": { "type": "Point", "coordinates": [ -60.653455, -32.94548] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Brigadier Lopez" }, "id": 83444},
       { "geometry": { "type": "Point", "coordinates": [ -60.650176, -32.964602] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Pellegrinet I (obra)" }, "id": 83445},
       { "geometry": { "type": "Point", "coordinates": [ -60.633126, -32.949726] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Sarmiento" }, "id": 83447},
       { "geometry": { "type": "Point", "coordinates": [ -60.65921, -32.935499] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Instituto Nº 8025 Virgen del Rosario" }, "id": 83449},
       { "geometry": { "type": "Point", "coordinates": [ -60.645343, -32.958217] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio NOB" }, "id": 83453},
       { "geometry": { "type": "Point", "coordinates": [ -60.631324, -32.94661] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Complejo Belgrano Centro" }, "id": 83462},
       { "geometry": { "type": "Point", "coordinates": [ -60.653778, -32.944478] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  OsPeCon Construir Salud" }, "id": 83464},
       { "geometry": { "type": "Point", "coordinates": [ -60.649876, -32.942034] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Plaza Ciivica Sede del Gob. de la Provincia en Rosario" }, "id": 83467},
       { "geometry": { "type": "Point", "coordinates": [ -60.651511, -32.948551] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Federada Salud" }, "id": 83468},
       { "geometry": { "type": "Point", "coordinates": [ -60.643717, -32.95452] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Universidad Tecnologica Nacional" }, "id": 83469},
       { "geometry": { "type": "Point", "coordinates": [ -60.655798, -32.964305] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Dir. Gral de Transito" }, "id": 83470},
       { "geometry": { "type": "Point", "coordinates": [ -60.655627, -32.963626] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela de Jardineriia" }, "id": 83471},
       { "geometry": { "type": "Point", "coordinates": [ -60.646054, -32.940026] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Mutual de Socios AMR" }, "id": 83473},
       { "geometry": { "type": "Point", "coordinates": [ -60.654086, -32.945698] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Misericordia" }, "id": 83477},
       { "geometry": { "type": "Point", "coordinates": [ -60.651707, -32.943848] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Jardiin Escuela Normal 2 J. M. Gutierrez" }, "id": 83478},
       { "geometry": { "type": "Point", "coordinates": [ -60.629373, -32.957578] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Primaria Nº 58 Juan B. Alberdi" }, "id": 83485},
       { "geometry": { "type": "Point", "coordinates": [ -60.639112, -32.93921] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Jardiin OSECAC" }, "id": 83488},
       { "geometry": { "type": "Point", "coordinates": [ -60.650626, -32.930254] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Silos Davis" }, "id": 83490},
       { "geometry": { "type": "Point", "coordinates": [ -60.645625, -32.940725] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Aleman - Escuela primaria" }, "id": 83494},
       { "geometry": { "type": "Point", "coordinates": [ -60.652595, -32.953859] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Sanatorio Plaza" }, "id": 83495},
       { "geometry": { "type": "Point", "coordinates": [ -60.629436, -32.955605] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela DINAD nº 1146" }, "id": 83498},
       { "geometry": { "type": "Point", "coordinates": [ -60.651237, -32.949563] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Sagrado Corazon" }, "id": 83499},
       { "geometry": { "type": "Point", "coordinates": [ -60.629591, -32.952499] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio de La Salle" }, "id": 83500},
       { "geometry": { "type": "Point", "coordinates": [ -60.643444, -32.950646] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Esc. Normal nº 1" }, "id": 83501},
       { "geometry": { "type": "Point", "coordinates": [ -60.654121, -32.948125] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 432 Bernardino Rivadavia" }, "id": 83502},
       { "geometry": { "type": "Point", "coordinates": [ -60.649451, -32.950304] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Primaria Nº 68 Leandro N. Alem" }, "id": 83503},
       { "geometry": { "type": "Point", "coordinates": [ -60.65321, -32.942225] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Superior de Comercio Nº 49 Juan J. de Urquiza" }, "id": 83504},
       { "geometry": { "type": "Point", "coordinates": [ -60.634637, -32.960343] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Español" }, "id": 83506},
       { "geometry": { "type": "Point", "coordinates": [ -60.650804, -32.944009] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Facultad de Derecho UNR" }, "id": 83512},
       { "geometry": { "type": "Point", "coordinates": [ -60.635048, -32.958536] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Madre Cabrini" }, "id": 83513},
       { "geometry": { "type": "Point", "coordinates": [ -60.656002, -32.938527] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  EET Nº 464 (Ex Nº 2) Ing. y Dr. Manuel Bahiia" }, "id": 83514},
       { "geometry": { "type": "Point", "coordinates": [ -60.644071, -32.956499] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Universidad del Centro Educativo Latinoamericano" }, "id": 83515},
       { "geometry": { "type": "Point", "coordinates": [ -60.654504, -32.949646] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Facultad de Ciencias Economicas UNR" }, "id": 83516},
       { "geometry": { "type": "Point", "coordinates": [ -60.628893, -32.959214] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Facultad de Ingenieriia UNR" }, "id": 83517},
       { "geometry": { "type": "Point", "coordinates": [ -60.656361, -32.935734] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 56 Almafuerte" }, "id": 83519},
       { "geometry": { "type": "Point", "coordinates": [ -60.631635, -32.947891] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  EEMPI Nº 8004 Liceo Avellaneda" }, "id": 83521},
       { "geometry": { "type": "Point", "coordinates": [ -60.64947, -32.937241] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Medio Luis F. Leloir" }, "id": 83522},
       { "geometry": { "type": "Point", "coordinates": [ -60.655261, -32.937417] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Complejo Instituto Belgrano" }, "id": 83525},
       { "geometry": { "type": "Point", "coordinates": [ -60.644895, -32.949412] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Bialik" }, "id": 83526},
       { "geometry": { "type": "Point", "coordinates": [ -60.625776, -32.956212] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela de Enseñanza Media Nº 430 Domingo F. Sarmiento" }, "id": 83527},
       { "geometry": { "type": "Point", "coordinates": [ -60.64264, -32.964914] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Rosario Bus" }, "id": 83539},
       { "geometry": { "type": "Point", "coordinates": [ -60.637085, -32.944567] },
                "type": "Feature", "properties": { "popupContent": "Centor de recepcion Instituto Municipal de Prevision Social" }, "id": 83540},
       { "geometry": { "type": "Point", "coordinates": [ -60.643514, -32.935875] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio Brown" }, "id": 83548},
       { "geometry": { "type": "Point", "coordinates": [ -60.657016, -32.942298] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Supermercado Carrefour" }, "id": 83551},
       { "geometry": { "type": "Point", "coordinates": [ -60.630512, -32.956261] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Hospital Provincial" }, "id": 83558},
       { "geometry": { "type": "Point", "coordinates": [ -60.632805, -32.971307] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Primaria Nº 1235 Constancio C. Vigil" }, "id": 83561},
       { "geometry": { "type": "Point", "coordinates": [ -60.644222, -32.940926] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  All Medicine" }, "id": 83562},
       { "geometry": { "type": "Point", "coordinates": [ -60.641496, -32.941583] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Asociacion de Empleados de Comercio Centro" }, "id": 83563},
       { "geometry": { "type": "Point", "coordinates": [ -60.638473, -32.963281] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Centro de diia Trayectoria" }, "id": 83568},
       { "geometry": { "type": "Point", "coordinates": [ -60.640874, -32.944925] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Juzgados Federales Civiles" }, "id": 83577},
       { "geometry": { "type": "Point", "coordinates": [ -60.64117, -32.951989] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Proveeduriia Municipal" }, "id": 83581},
       { "geometry": { "type": "Point", "coordinates": [ -60.650894, -32.946087] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Urgencias" }, "id": 83583},
       { "geometry": { "type": "Point", "coordinates": [ -60.650054, -32.940805] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Veterinaria CIMA I" }, "id": 83584},
       { "geometry": { "type": "Point", "coordinates": [ -60.651158, -32.949301] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Veterinaria CIMA II" }, "id": 83585},
       { "geometry": { "type": "Point", "coordinates": [ -60.660651, -32.962761] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  - Estadio Municipal" }, "id": 83591},
       { "geometry": { "type": "Point", "coordinates": [ -60.654537, -32.942406] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  OSUNR" }, "id": 83602},
       { "geometry": { "type": "Point", "coordinates": [ -60.654009, -32.945393] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Tribunales Federales" }, "id": 83603},
       { "geometry": { "type": "Point", "coordinates": [ -60.642107, -32.953589] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Tecnica Nº 294 Crucero General Belgrano" }, "id": 83604},
       { "geometry": { "type": "Point", "coordinates": [ -60.643948, -32.941141] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela de Cocina Mas" }, "id": 83608},
       { "geometry": { "type": "Point", "coordinates": [ -60.646721, -32.948651] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Maria Auxiliadora" }, "id": 83615},
       { "geometry": { "type": "Point", "coordinates": [ -60.629266, -32.969828] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Carrefour Local 033" }, "id": 83627},
       { "geometry": { "type": "Point", "coordinates": [ -60.637257, -32.944496] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio Rochdale V" }, "id": 83628},
       { "geometry": { "type": "Point", "coordinates": [ -60.656389, -32.935729] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  E.E.S.O Nº 406 Dr. Salvador Mazza" }, "id": 83631},
       { "geometry": { "type": "Point", "coordinates": [ -60.640176, -32.937643] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio Punta Divisadero" }, "id": 83638},
       { "geometry": { "type": "Point", "coordinates": [ -60.653493, -32.945629] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  OSDE" }, "id": 83640},
       { "geometry": { "type": "Point", "coordinates": [ -60.655009, -32.971392] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Supermercado Unico" }, "id": 83642},
       { "geometry": { "type": "Point", "coordinates": [ -60.636747, -32.975397] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Cablevision" }, "id": 83644},
       { "geometry": { "type": "Point", "coordinates": [ -60.638085, -32.966027] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Esc. Especial Nº 1330 Connar" }, "id": 83648},
       { "geometry": { "type": "Point", "coordinates": [ -60.632802, -32.953203] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 53 Bernardino Rivadavia" }, "id": 83649},
       { "geometry": { "type": "Point", "coordinates": [ -60.637692, -32.950183] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  CC Roberto Fontanarrosa" }, "id": 83653},
       { "geometry": { "type": "Point", "coordinates": [ -60.643958, -32.951409] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Instituto Universitario del Gran Rosario -IUGR-" }, "id": 83655},
       { "geometry": { "type": "Point", "coordinates": [ -60.639327, -32.951628] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Plataforma Lavarden" }, "id": 83656},
       { "geometry": { "type": "Point", "coordinates": [ -60.654328, -32.931515] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Dir. de Control Urbano" }, "id": 83657},
       { "geometry": { "type": "Point", "coordinates": [ -60.636165, -32.940464] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Club Universitario" }, "id": 83658},
       { "geometry": { "type": "Point", "coordinates": [ -60.626682, -32.949635] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Estacion Fluvial Puerto Rosario" }, "id": 83661},
       { "geometry": { "type": "Point", "coordinates": [ -60.634658, -32.949382] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Cliinica del Higado" }, "id": 83668},
       { "geometry": { "type": "Point", "coordinates": [ -60.633079, -32.948215] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Secretariia de Promocion Social" }, "id": 83669},
       { "geometry": { "type": "Point", "coordinates": [ -60.646561, -32.963041] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Trial International S.A" }, "id": 83670},
       { "geometry": { "type": "Point", "coordinates": [ -60.648555, -32.96392] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Bauen 81/82" }, "id": 83673},
       { "geometry": { "type": "Point", "coordinates": [ -60.648501, -32.963706] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Bauen 83" }, "id": 83674},
       { "geometry": { "type": "Point", "coordinates": [ -60.635389, -32.964647] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Sipel" }, "id": 83680},
       { "geometry": { "type": "Point", "coordinates": [ -60.655314, -32.943487] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Domingo Juan Taleti SA" }, "id": 83681},
       { "geometry": { "type": "Point", "coordinates": [ -60.646712, -32.950868] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Coto - sucursal 099" }, "id": 83684},
       { "geometry": { "type": "Point", "coordinates": [ -60.649312, -32.966934] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Picar SRL" }, "id": 83685},
       { "geometry": { "type": "Point", "coordinates": [ -60.64483, -32.941468] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Coto - sucursal 097" }, "id": 83686},
       { "geometry": { "type": "Point", "coordinates": [ -60.645358, -32.961136] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Taller Ismael Alvarado e Hijo" }, "id": 83690},
       { "geometry": { "type": "Point", "coordinates": [ -60.642573, -32.947237] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Intagro S.A." }, "id": 83700},
       { "geometry": { "type": "Point", "coordinates": [ -60.663071, -32.966233] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  SUMAR" }, "id": 83708},
       { "geometry": { "type": "Point", "coordinates": [ -60.662793, -32.96512] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Frigofe" }, "id": 83709},
       { "geometry": { "type": "Point", "coordinates": [ -60.625408, -32.973085] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Club Atletico Biblioteca Popular Porvenir" }, "id": 116508},
       { "geometry": { "type": "Point", "coordinates": [ -60.62932, -32.955624] },
                "type": "Feature", "properties": { "popupContent": "Taller Protegido Rosario" }, "id": 123745},
       { "geometry": { "type": "Point", "coordinates": [ -60.642673, -32.969617] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Concesionario Peugeot" }, "id": 119552},
       { "geometry": { "type": "Point", "coordinates": [ -60.634426, -32.96748] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119818},
       { "geometry": { "type": "Point", "coordinates": [ -60.651596, -32.945349] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119810},
       { "geometry": { "type": "Point", "coordinates": [ -60.634818, -32.974737] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela Rep del Peru" }, "id": 74911},
       { "geometry": { "type": "Point", "coordinates": [ -60.623541, -32.966227] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Recepcion: Facultad de Psicologia UNR" }, "id": 74912},
       { "geometry": { "type": "Point", "coordinates": [ -60.627682, -32.96936] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Recepcion: Escuela Nº 1265" }, "id": 75265},
       { "geometry": { "type": "Point", "coordinates": [ -60.645769, -32.964395] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Recepcion: Escuela Normal Nº3" }, "id": 75266},
       { "geometry": { "type": "Point", "coordinates": [ -60.636274, -32.974816] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Jardin Nº 71" }, "id": 75618},
       { "geometry": { "type": "Point", "coordinates": [ -60.62397, -32.966151] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Recepcion: UNR" }, "id": 75619},
       { "geometry": { "type": "Point", "coordinates": [ -60.627682, -32.96936] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela Nº 3033" }, "id": 75972},
       { "geometry": { "type": "Point", "coordinates": [ -60.653643, -32.971637] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: ARCOR" }, "id": 76324},
       { "geometry": { "type": "Point", "coordinates": [ -60.62397, -32.966151] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Recepcion: UNR" }, "id": 76326},
       { "geometry": { "type": "Point", "coordinates": [ -60.630126, -32.969765] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Recepcion: escuela Nº 465" }, "id": 76679},
       { "geometry": { "type": "Point", "coordinates": [ -60.657564, -32.961769] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Museo de la ciudad" }, "id": 76684},
       { "geometry": { "type": "Point", "coordinates": [ -60.658453, -32.956861] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Jardin de los Niños" }, "id": 76686},
       { "geometry": { "type": "Point", "coordinates": [ -60.654565, -32.968155] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Hospitl Vilela" }, "id": 77031},
       { "geometry": { "type": "Point", "coordinates": [ -60.6405, -32.975188] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela Nº 658" }, "id": 77032},
       { "geometry": { "type": "Point", "coordinates": [ -60.62397, -32.966151] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Facultad UNR" }, "id": 77033},
       { "geometry": { "type": "Point", "coordinates": [ -60.640687, -32.969435] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Nº 1" }, "id": 77738},
       { "geometry": { "type": "Point", "coordinates": [ -60.640329, -32.975495] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela Nº 2066" }, "id": 77739},
       { "geometry": { "type": "Point", "coordinates": [ -60.624771, -32.965686] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: CEDIF Jardin Puerto alegria" }, "id": 82983},
       { "geometry": { "type": "Point", "coordinates": [ -60.62409, -32.966208] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela dentro de la Siberia" }, "id": 82984},
       { "geometry": { "type": "Point", "coordinates": [ -60.636217, -32.962027] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela Ameghino" }, "id": 82985},
       { "geometry": { "type": "Point", "coordinates": [ -60.647338, -32.95912] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Universidad Austral" }, "id": 82986},
       { "geometry": { "type": "Point", "coordinates": [ -60.642673, -32.969617] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: sionario Peugeot" }, "id": 76677},
       { "geometry": { "type": "Point", "coordinates": [ -60.626481, -32.969436] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: CONICET" }, "id": 82991},
       { "geometry": { "type": "Point", "coordinates": [ -60.632737, -32.942328] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84620},
       { "geometry": { "type": "Point", "coordinates": [ -60.645882, -32.943477] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 120032},
       { "geometry": { "type": "Point", "coordinates": [ -60.638868, -32.942798] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 120033},
       { "geometry": { "type": "Point", "coordinates": [ -60.643953, -32.946988] },
                "type": "Feature", "properties": { "popupContent": "Personal Rosario Centro" }, "id": 120277},
       { "geometry": { "type": "Point", "coordinates": [ -60.641494, -32.965184] },
                "type": "Feature", "properties": { "popupContent": "Personal  Rosario Sur" }, "id": 120275},
       { "geometry": { "type": "Point", "coordinates": [ -60.643957, -32.963075] },
                "type": "Feature", "properties": { "popupContent": "Personal C.C.T." }, "id": 120274},
       { "geometry": { "type": "Point", "coordinates": [ -60.631946, -32.947834] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118873},
       { "geometry": { "type": "Point", "coordinates": [ -60.635042, -32.954652] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118868},
       { "geometry": { "type": "Point", "coordinates": [ -60.634921, -32.962773] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118876},
       { "geometry": { "type": "Point", "coordinates": [ -60.636583, -32.963503] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118879},
       { "geometry": { "type": "Point", "coordinates": [ -60.640602, -32.965577] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118877},
       { "geometry": { "type": "Point", "coordinates": [ -60.639754, -32.940452] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118871},
       { "geometry": { "type": "Point", "coordinates": [ -60.643534, -32.97306] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118896},
       { "geometry": { "type": "Point", "coordinates": [ -60.651404, -32.937299] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118897},
       { "geometry": { "type": "Point", "coordinates": [ -60.643534, -32.97306] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119135},
       { "geometry": { "type": "Point", "coordinates": [ -60.656353, -32.940648] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119388},
       { "geometry": { "type": "Point", "coordinates": [ -60.657575, -32.935792] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119141},
       { "geometry": { "type": "Point", "coordinates": [ -60.642897, -32.972326] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119393},
       { "geometry": { "type": "Point", "coordinates": [ -60.642087, -32.956853] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119136},
       { "geometry": { "type": "Point", "coordinates": [ -60.629949, -32.947368] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119485},
       { "geometry": { "type": "Point", "coordinates": [ -60.639493, -32.949045] },
                "type": "Feature", "properties": { "popupContent": "Supermercados Cadena DAR" }, "id": 129255},
       { "geometry": { "type": "Point", "coordinates": [ -60.644611, -32.934939] },
                "type": "Feature", "properties": { "popupContent": "Edificio Pilares del Rio" }, "id": 129252},
       { "geometry": { "type": "Point", "coordinates": [ -60.650901, -32.933079] },
                "type": "Feature", "properties": { "popupContent": "Queens Boulevard" }, "id": 129248},
       { "geometry": { "type": "Point", "coordinates": [ -60.63287, -32.954744] },
                "type": "Feature", "properties": { "popupContent": "Edificio 25 de Diciembre" }, "id": 129273},
       { "geometry": { "type": "Point", "coordinates": [ -60.641378, -32.948716] },
                "type": "Feature", "properties": { "popupContent": "Supermercados Cadena DAR" }, "id": 129256},
       { "geometry": { "type": "Point", "coordinates": [ -60.644621, -32.940559] },
                "type": "Feature", "properties": { "popupContent": "Supermercado Coto - sucursal 097 (deposito)" }, "id": 129253},
       { "geometry": { "type": "Point", "coordinates": [ -60.634838, -32.948284] },
                "type": "Feature", "properties": { "popupContent": "Supermercados Cadena DAR" }, "id": 129254},
       { "geometry": { "type": "Point", "coordinates": [ -60.642508, -32.953518] },
                "type": "Feature", "properties": { "popupContent": "Edificio" }, "id": 129251},
       { "geometry": { "type": "Point", "coordinates": [ -60.638375, -32.94654] },
                "type": "Feature", "properties": { "popupContent": "Falabella Rosario" }, "id": 129286},
       { "geometry": { "type": "Point", "coordinates": [ -60.657251, -32.947516] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84600},
       { "geometry": { "type": "Point", "coordinates": [ -60.638903, -32.945021] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84601},
       { "geometry": { "type": "Point", "coordinates": [ -60.638821, -32.950064] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84606},
       { "geometry": { "type": "Point", "coordinates": [ -60.624091, -32.96613] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84610},
       { "geometry": { "type": "Point", "coordinates": [ -60.631908, -32.956004] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84613},
       { "geometry": { "type": "Point", "coordinates": [ -60.652867, -32.940869] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84623},
       { "geometry": { "type": "Point", "coordinates": [ -60.652567, -32.953864] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84633},
       { "geometry": { "type": "Point", "coordinates": [ -60.635961, -32.952246] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84635},
       { "geometry": { "type": "Point", "coordinates": [ -60.62676, -32.949798] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84641},
       { "geometry": { "type": "Point", "coordinates": [ -60.626157, -32.963644] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84647},
       { "geometry": { "type": "Point", "coordinates": [ -60.648837, -32.949172] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84648},
       { "geometry": { "type": "Point", "coordinates": [ -60.649928, -32.967509] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84654},
       { "geometry": { "type": "Point", "coordinates": [ -60.640497, -32.943408] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84658},
       { "geometry": { "type": "Point", "coordinates": [ -60.649993, -32.930709] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84621},
       { "geometry": { "type": "Point", "coordinates": [ -60.645462, -32.957379] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84663},
       { "geometry": { "type": "Point", "coordinates": [ -60.641196, -32.940403] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84664},
       { "geometry": { "type": "Point", "coordinates": [ -60.627224, -32.951721] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84674},
       { "geometry": { "type": "Point", "coordinates": [ -60.625306, -32.953687] },
                "type": "Feature", "properties": { "popupContent": "Queens Deck" }, "id": 126385} ] };
