var centro = {
          "type": "FeatureCollection",
          "features": [
       { "geometry": { "type": "Point", "coordinates": [ -60.691072, -32.947229] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. Primaria Nº 1324 Principe de Paz" }, "id": 69177},
       { "geometry": { "type": "Point", "coordinates": [ -60.674524, -32.949724] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: ESC. PROVINCIAL DE SALTA" }, "id": 69172},
       { "geometry": { "type": "Point", "coordinates": [ -60.699502, -32.944635] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Ctro. De Salud Jean Henry Dunant" }, "id": 69169},

       { "geometry": { "type": "Point", "coordinates": [ -60.665016, -32.963527] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Club Atletico Provincial" }, "id": 103227},
       { "geometry": { "type": "Point", "coordinates": [ -60.647812, -32.940932] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Administracion Provincial de Impuestos (A.P.I)" }, "id": 116005},
       { "geometry": { "type": "Point", "coordinates": [ -60.668891, -32.950019] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Complejo Malvinas Argentinas Futbol infantil NOB" }, "id": 67950},
       { "geometry": { "type": "Point", "coordinates": [ -60.667731, -32.932779] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Cargill S.A.C.I." }, "id": 67952},
       { "geometry": { "type": "Point", "coordinates": [ -60.672862, -32.931591] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. Nuestra Sra. de Guadalupe" }, "id": 69123},
       { "geometry": { "type": "Point", "coordinates": [ -60.689457, -32.935634] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc N 9045: Instituto Zona Oeste" }, "id": 69176},
       { "geometry": { "type": "Point", "coordinates": [ -60.679309, -32.940862] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Jardin nº 38 Magdalena Guemes" }, "id": 69174},
       { "geometry": { "type": "Point", "coordinates": [ -60.666685, -32.934246] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Complejo Gurruchaga" }, "id": 69173},
       { "geometry": { "type": "Point", "coordinates": [ -60.694466, -32.937881] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela Luis Calderon" }, "id": 70390},
       { "geometry": { "type": "Point", "coordinates": [ -60.688328, -32.933607] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Club Rosario Lawn Tennis 1" }, "id": 70398},
       { "geometry": { "type": "Point", "coordinates": [ -60.683387, -32.936765] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Club Atletico Atlanta" }, "id": 70397},
       { "geometry": { "type": "Point", "coordinates": [ -60.679955, -32.939981] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. J C Paz nº 525" }, "id": 70396},
       { "geometry": { "type": "Point", "coordinates": [ -60.659221, -32.942786] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc.Tecnica Nº 625" }, "id": 70393},
       { "geometry": { "type": "Point", "coordinates": [ -60.666473, -32.934056] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Complejo Gurruchaga Sec" }, "id": 70395},
       { "geometry": { "type": "Point", "coordinates": [ -60.677779, -32.934977] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Micropack" }, "id": 83014},
       { "geometry": { "type": "Point", "coordinates": [ -60.681843, -32.944914] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Universidad Catolica Argentina Centro Franciscano de Estudio y Desarrollo Region" }, "id": 67954},
       { "geometry": { "type": "Point", "coordinates": [ -60.680316, -32.933501] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Patio Parada" }, "id": 67953},
       { "geometry": { "type": "Point", "coordinates": [ -60.668929, -32.93621] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. Pedro Goyena nº 77" }, "id": 67951},
       { "geometry": { "type": "Point", "coordinates": [ -60.647484, -32.943792] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Colegio Adoratrices" }, "id": 67949},
       { "geometry": { "type": "Point", "coordinates": [ -60.695272, -32.940753] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. Nuestra Sra Pompeya (Prim: 1183, Sec: 3173 y Nivel Inicial: 1284)" }, "id": 67947},
       { "geometry": { "type": "Point", "coordinates": [ -60.693788, -32.941194] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Club Atletico Libertad" }, "id": 67946},
       { "geometry": { "type": "Point", "coordinates": [ -60.652807, -32.95494] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: La Gallega supermercados" }, "id": 84659},
       { "geometry": { "type": "Point", "coordinates": [ -60.665395, -32.945995] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Bellia y Lianza S.A." }, "id": 116507},
       { "geometry": { "type": "Point", "coordinates": [ -60.644475, -32.938133] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Edificio Irupe" }, "id": 116003},
       { "geometry": { "type": "Point", "coordinates": [ -60.663105, -32.961398] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: I.C.E.F Instituto Superior de Educacion Fisica" }, "id": 116002},
       { "geometry": { "type": "Point", "coordinates": [ -60.682004, -32.951599] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro habitacional Santiago Apostol" }, "id": 108969},
       { "geometry": { "type": "Point", "coordinates": [ -60.663217, -32.938693] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Facultad de Cs. Bioquiimicas y Farmacia" }, "id": 83682},
       { "geometry": { "type": "Point", "coordinates": [ -60.655204, -32.950129] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Trasera" }, "id": 119813},
       { "geometry": { "type": "Point", "coordinates": [ -60.671086, -32.951655] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Pontificia Universidad Catolica Argentina" }, "id": 83430},
       { "geometry": { "type": "Point", "coordinates": [ -60.698643, -32.939388] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Esc. Nº 120 Jose Maria Rondeau" }, "id": 83547},
       { "geometry": { "type": "Point", "coordinates": [ -60.648109, -32.946274] },
                "type": "Feature", "properties": { "popupContent": "Queens centro" }, "id": 127314},
       { "geometry": { "type": "Point", "coordinates": [ -60.683715, -32.954261] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Rosario Lawn Tennis II" }, "id": 83717},
       { "geometry": { "type": "Point", "coordinates": [ -60.664948, -32.951126] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Salud Maiztegui" }, "id": 83448},
       { "geometry": { "type": "Point", "coordinates": [ -60.64805, -32.936255] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 54 Manuel Belgrano" }, "id": 83401},
       { "geometry": { "type": "Point", "coordinates": [ -60.665301, -32.952694] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Dir. de Alumbrado" }, "id": 83408},
       { "geometry": { "type": "Point", "coordinates": [ -60.665244, -32.952704] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Direrccion Señalizacion No Luminosa" }, "id": 83412},
       { "geometry": { "type": "Point", "coordinates": [ -60.65125, -32.946199] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Instituto de la Mujer" }, "id": 83413},
       { "geometry": { "type": "Point", "coordinates": [ -60.654874, -32.9381] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  OCA - Organizacion Coordinadora Argentina" }, "id": 83417},
       { "geometry": { "type": "Point", "coordinates": [ -60.65125, -32.946199] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  CEMAR" }, "id": 83424},
       { "geometry": { "type": "Point", "coordinates": [ -60.669194, -32.955007] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: IMUSA" }, "id": 83463},
       { "geometry": { "type": "Point", "coordinates": [ -60.666007, -32.939885] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: SUMAR" }, "id": 83480},
       { "geometry": { "type": "Point", "coordinates": [ -60.655339, -32.962481] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Dir. Gral. de Parques y Paseo" }, "id": 83461},
       { "geometry": { "type": "Point", "coordinates": [ -60.656715, -32.930826] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Sec. Cultura y Educacion" }, "id": 83456},
       { "geometry": { "type": "Point", "coordinates": [ -60.664376, -32.953298] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Sec. Ambiente y Esp. Publico" }, "id": 83455},
       { "geometry": { "type": "Point", "coordinates": [ -60.695971, -32.950368] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Azcuenaga Sur" }, "id": 83481},
       { "geometry": { "type": "Point", "coordinates": [ -60.651707, -32.943848] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Secundaria Normal 2 J. M. Gutierrez" }, "id": 83436},
       { "geometry": { "type": "Point", "coordinates": [ -60.655688, -32.933412] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Blue Connect (Call Center) Point" }, "id": 83437},
       { "geometry": { "type": "Point", "coordinates": [ -60.657446, -32.953917] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio Museion Construcciones Fundar" }, "id": 83438},
       { "geometry": { "type": "Point", "coordinates": [ -60.683396, -32.954928] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  SIDERCO" }, "id": 83439},
       { "geometry": { "type": "Point", "coordinates": [ -60.653859, -32.947085] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Sancor Seguros Centro Medico Laboral" }, "id": 83442},
       { "geometry": { "type": "Point", "coordinates": [ -60.663181, -32.939421] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Tata SA" }, "id": 83443},
       { "geometry": { "type": "Point", "coordinates": [ -60.653455, -32.94548] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Brigadier Lopez" }, "id": 83444},
       { "geometry": { "type": "Point", "coordinates": [ -60.650176, -32.964602] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Pellegrinet I (obra)" }, "id": 83445},
       { "geometry": { "type": "Point", "coordinates": [ -60.677857, -32.944807] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Coto - sucursal 095" }, "id": 83446},
       { "geometry": { "type": "Point", "coordinates": [ -60.65921, -32.935499] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Instituto Nº 8025 Virgen del Rosario" }, "id": 83449},
       { "geometry": { "type": "Point", "coordinates": [ -60.653778, -32.944478] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  OsPeCon Construir Salud" }, "id": 83464},
       { "geometry": { "type": "Point", "coordinates": [ -60.649876, -32.942034] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Plaza Ciivica Sede del Gob. de la Provincia en Rosario" }, "id": 83467},
       { "geometry": { "type": "Point", "coordinates": [ -60.651511, -32.948551] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Federada Salud" }, "id": 83468},
       { "geometry": { "type": "Point", "coordinates": [ -60.655798, -32.964305] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Dir. Gral de Transito" }, "id": 83470},
       { "geometry": { "type": "Point", "coordinates": [ -60.655627, -32.963626] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela de Jardineriia" }, "id": 83471},
       { "geometry": { "type": "Point", "coordinates": [ -60.646054, -32.940026] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Mutual de Socios AMR" }, "id": 83473},
       { "geometry": { "type": "Point", "coordinates": [ -60.654086, -32.945698] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Misericordia" }, "id": 83477},
       { "geometry": { "type": "Point", "coordinates": [ -60.651707, -32.943848] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Jardiin Escuela Normal 2 J. M. Gutierrez" }, "id": 83478},
       { "geometry": { "type": "Point", "coordinates": [ -60.666059, -32.94473] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio del Sol" }, "id": 83486},
       { "geometry": { "type": "Point", "coordinates": [ -60.650626, -32.930254] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Silos Davis" }, "id": 83490},
       { "geometry": { "type": "Point", "coordinates": [ -60.662442, -32.945562] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Juan Arzeno" }, "id": 83491},
       { "geometry": { "type": "Point", "coordinates": [ -60.645625, -32.940725] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Aleman - Escuela primaria" }, "id": 83494},
       { "geometry": { "type": "Point", "coordinates": [ -60.652595, -32.953859] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Sanatorio Plaza" }, "id": 83495},
       { "geometry": { "type": "Point", "coordinates": [ -60.681276, -32.946557] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Hospital Carrasco" }, "id": 83497},
       { "geometry": { "type": "Point", "coordinates": [ -60.651237, -32.949563] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Sagrado Corazon" }, "id": 83499},
       { "geometry": { "type": "Point", "coordinates": [ -60.654121, -32.948125] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 432 Bernardino Rivadavia" }, "id": 83502},
       { "geometry": { "type": "Point", "coordinates": [ -60.649451, -32.950304] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Primaria Nº 68 Leandro N. Alem" }, "id": 83503},
       { "geometry": { "type": "Point", "coordinates": [ -60.65321, -32.942225] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Superior de Comercio Nº 49 Juan J. de Urquiza" }, "id": 83504},
       { "geometry": { "type": "Point", "coordinates": [ -60.663299, -32.937718] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Ntra. Sra. de la Misericordia - Particular Nº 1117" }, "id": 83505},
       { "geometry": { "type": "Point", "coordinates": [ -60.675674, -32.939832] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 90 Franklin D. Roosevelt" }, "id": 83507},
       { "geometry": { "type": "Point", "coordinates": [ -60.663005, -32.944566] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela de Enseñanza Media Nº 404 Dr. Lisandro de la Torre" }, "id": 83509},
       { "geometry": { "type": "Point", "coordinates": [ -60.66087, -32.939354] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Natalio Automotores" }, "id": 83510},
       { "geometry": { "type": "Point", "coordinates": [ -60.6638, -32.950914] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela de Enseñanza Tecnica Nº 288 Osvaldo Magnasco" }, "id": 83511},
       { "geometry": { "type": "Point", "coordinates": [ -60.650804, -32.944009] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Facultad de Derecho UNR" }, "id": 83512},
       { "geometry": { "type": "Point", "coordinates": [ -60.656002, -32.938527] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  EET Nº 464 (Ex Nº 2) Ing. y Dr. Manuel Bahiia" }, "id": 83514},
       { "geometry": { "type": "Point", "coordinates": [ -60.654504, -32.949646] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Facultad de Ciencias Economicas UNR" }, "id": 83516},
       { "geometry": { "type": "Point", "coordinates": [ -60.673931, -32.943775] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Media Nº 258 Soldado Arg. Primaria E. Zeballos y EEMPA" }, "id": 83518},
       { "geometry": { "type": "Point", "coordinates": [ -60.656361, -32.935734] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 56 Almafuerte" }, "id": 83519},
       { "geometry": { "type": "Point", "coordinates": [ -60.665376, -32.939998] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Facultad de Ciencias Medicas UNR" }, "id": 83520},
       { "geometry": { "type": "Point", "coordinates": [ -60.64947, -32.937241] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Medio Luis F. Leloir" }, "id": 83522},
       { "geometry": { "type": "Point", "coordinates": [ -60.661638, -32.936756] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Tecnica Nº 632 Gabriel Carrasco" }, "id": 83523},
       { "geometry": { "type": "Point", "coordinates": [ -60.655261, -32.937417] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Complejo Instituto Belgrano" }, "id": 83525},
       { "geometry": { "type": "Point", "coordinates": [ -60.693323, -32.938199] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  FAE" }, "id": 83533},
       { "geometry": { "type": "Point", "coordinates": [ -60.666997, -32.948467] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Cablevision" }, "id": 83537},
       { "geometry": { "type": "Point", "coordinates": [ -60.676644, -32.934294] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  LEM" }, "id": 83538},
       { "geometry": { "type": "Point", "coordinates": [ -60.664727, -32.954675] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Cementerio El Salvador" }, "id": 83541},
       { "geometry": { "type": "Point", "coordinates": [ -60.643514, -32.935875] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio Brown" }, "id": 83548},
       { "geometry": { "type": "Point", "coordinates": [ -60.657016, -32.942298] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Supermercado Carrefour" }, "id": 83551},
       { "geometry": { "type": "Point", "coordinates": [ -60.662866, -32.9511] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Sagrada Familia De Rosario" }, "id": 83554},
       { "geometry": { "type": "Point", "coordinates": [ -60.644222, -32.940926] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  All Medicine" }, "id": 83562},
       { "geometry": { "type": "Point", "coordinates": [ -60.665161, -32.951886] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  ASU Centro" }, "id": 83564},
       { "geometry": { "type": "Point", "coordinates": [ -60.669292, -32.933412] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Cargill" }, "id": 83565},
       { "geometry": { "type": "Point", "coordinates": [ -60.668813, -32.953491] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Centro de Monitoreo de la Movilidad" }, "id": 83569},
       { "geometry": { "type": "Point", "coordinates": [ -60.66921, -32.959266] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Nº 610 Republica de Bolivia" }, "id": 83575},
       { "geometry": { "type": "Point", "coordinates": [ -60.662531, -32.939537] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Prosegur" }, "id": 83580},
       { "geometry": { "type": "Point", "coordinates": [ -60.650894, -32.946087] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Urgencias" }, "id": 83583},
       { "geometry": { "type": "Point", "coordinates": [ -60.650054, -32.940805] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Veterinaria CIMA I" }, "id": 83584},
       { "geometry": { "type": "Point", "coordinates": [ -60.651158, -32.949301] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Veterinaria CIMA II" }, "id": 83585},
       { "geometry": { "type": "Point", "coordinates": [ -60.660651, -32.962761] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  - Estadio Municipal" }, "id": 83591},
       { "geometry": { "type": "Point", "coordinates": [ -60.678666, -32.944662] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela Pestalozzi Nº67" }, "id": 83599},
       { "geometry": { "type": "Point", "coordinates": [ -60.681161, -32.945488] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Direccion de Bioquimica" }, "id": 83601},
       { "geometry": { "type": "Point", "coordinates": [ -60.654537, -32.942406] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  OSUNR" }, "id": 83602},
       { "geometry": { "type": "Point", "coordinates": [ -60.654009, -32.945393] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Tribunales Federales" }, "id": 83603},
       { "geometry": { "type": "Point", "coordinates": [ -60.643948, -32.941141] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Escuela de Cocina Mas" }, "id": 83608},
       { "geometry": { "type": "Point", "coordinates": [ -60.646721, -32.948651] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Colegio Maria Auxiliadora" }, "id": 83615},
       { "geometry": { "type": "Point", "coordinates": [ -60.667392, -32.952319] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Pellegrini Servicios S.R.L." }, "id": 83616},
       { "geometry": { "type": "Point", "coordinates": [ -60.669799, -32.952324] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Hospital de Emergencias Clemente Ãlvarez" }, "id": 83617},
       { "geometry": { "type": "Point", "coordinates": [ -60.684375, -32.958802] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  America Rosario SA" }, "id": 83619},
       { "geometry": { "type": "Point", "coordinates": [ -60.677397, -32.938559] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Edificio Lavalle" }, "id": 83621},
       { "geometry": { "type": "Point", "coordinates": [ -60.673463, -32.951229] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio" }, "id": 83629},
       { "geometry": { "type": "Point", "coordinates": [ -60.656389, -32.935729] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  E.E.S.O Nº 406 Dr. Salvador Mazza" }, "id": 83631},
       { "geometry": { "type": "Point", "coordinates": [ -60.669567, -32.960406] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Centro de diia La casa del pasaje" }, "id": 83635},
       { "geometry": { "type": "Point", "coordinates": [ -60.66531, -32.952559] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Dir. De Conrtol de Vectores" }, "id": 83639},
       { "geometry": { "type": "Point", "coordinates": [ -60.653493, -32.945629] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  OSDE" }, "id": 83640},
       { "geometry": { "type": "Point", "coordinates": [ -60.683948, -32.940669] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Life Gate" }, "id": 83641},
       { "geometry": { "type": "Point", "coordinates": [ -60.693488, -32.94941] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepicon Centro de Salud Maradona" }, "id": 83643},
       { "geometry": { "type": "Point", "coordinates": [ -60.670237, -32.951808] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Carrefour 032" }, "id": 83650},
       { "geometry": { "type": "Point", "coordinates": [ -60.654328, -32.931515] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Dir. de Control Urbano" }, "id": 83657},
       { "geometry": { "type": "Point", "coordinates": [ -60.68175, -32.945383] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Lem (Laboratorio de Especialidades Medicinales)" }, "id": 83659},
       { "geometry": { "type": "Point", "coordinates": [ -60.669473, -32.933656] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Teatro Vorterix Rosario" }, "id": 83667},
       { "geometry": { "type": "Point", "coordinates": [ -60.672672, -32.935536] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Edificio" }, "id": 83672},
       { "geometry": { "type": "Point", "coordinates": [ -60.648555, -32.96392] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Bauen 81/82" }, "id": 83673},
       { "geometry": { "type": "Point", "coordinates": [ -60.648501, -32.963706] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Bauen 83" }, "id": 83674},
       { "geometry": { "type": "Point", "coordinates": [ -60.664579, -32.951714] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Secretariia de Ambiente y Espacio Publico" }, "id": 83677},
       { "geometry": { "type": "Point", "coordinates": [ -60.678615, -32.963845] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Direc Soluciones Logiisticas" }, "id": 83679},
       { "geometry": { "type": "Point", "coordinates": [ -60.655314, -32.943487] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Domingo Juan Taleti SA" }, "id": 83681},
       { "geometry": { "type": "Point", "coordinates": [ -60.646712, -32.950868] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Coto - sucursal 099" }, "id": 83684},
       { "geometry": { "type": "Point", "coordinates": [ -60.64483, -32.941468] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Coto - sucursal 097" }, "id": 83686},
       { "geometry": { "type": "Point", "coordinates": [ -60.667314, -32.952333] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Empresa distribuidora Toledo SRL" }, "id": 83689},
       { "geometry": { "type": "Point", "coordinates": [ -60.678333, -32.940963] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Atlantic Sportsmen Club" }, "id": 83697},
       { "geometry": { "type": "Point", "coordinates": [ -60.665721, -32.966901] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Centro de Salud Fonavi 25" }, "id": 83701},
       { "geometry": { "type": "Point", "coordinates": [ -60.69446, -32.950124] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Metalurgica Matienzo S.R.L" }, "id": 83703},
       { "geometry": { "type": "Point", "coordinates": [ -60.697576, -32.948396] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Metalurgica Matienzo S.R.L" }, "id": 83704},
       { "geometry": { "type": "Point", "coordinates": [ -60.665762, -32.96715] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Jardiin Inti Huasi" }, "id": 83706},
       { "geometry": { "type": "Point", "coordinates": [ -60.663071, -32.966233] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  SUMAR" }, "id": 83708},
       { "geometry": { "type": "Point", "coordinates": [ -60.662793, -32.96512] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Frigofe" }, "id": 83709},
       { "geometry": { "type": "Point", "coordinates": [ -60.68767, -32.943042] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:  Neostar SA." }, "id": 83432},
       { "geometry": { "type": "Point", "coordinates": [ -60.682684, -32.954291] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Toyota Ginza" }, "id": 116519},
       { "geometry": { "type": "Point", "coordinates": [ -60.666396, -32.952497] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Trasera" }, "id": 84675},
       { "geometry": { "type": "Point", "coordinates": [ -60.666013, -32.934001] },
                "type": "Feature", "properties": { "popupContent": "Siscop srl" }, "id": 123746},
       { "geometry": { "type": "Point", "coordinates": [ -60.666162, -32.962463] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro de Recepcion: Estadio Municipal" }, "id": 75964},
       { "geometry": { "type": "Point", "coordinates": [ -60.676007, -32.957118] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Congelados del Sur" }, "id": 126777},
       { "geometry": { "type": "Point", "coordinates": [ -60.651596, -32.945349] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119810},
       { "geometry": { "type": "Point", "coordinates": [ -60.698374, -32.948961] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. Nº 63 Almirante Brown" }, "id": 77380},
       { "geometry": { "type": "Point", "coordinates": [ -60.666878, -32.96363] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119816},
       { "geometry": { "type": "Point", "coordinates": [ -60.676704, -32.962664] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela Nº 1115 San Jose" }, "id": 77038},
       { "geometry": { "type": "Point", "coordinates": [ -60.66493, -32.966663] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela Latinoamerica" }, "id": 76333},
       { "geometry": { "type": "Point", "coordinates": [ -60.657564, -32.961769] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Museo de la ciudad" }, "id": 76684},
       { "geometry": { "type": "Point", "coordinates": [ -60.658453, -32.956861] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Jardin de los Niños" }, "id": 76686},
       { "geometry": { "type": "Point", "coordinates": [ -60.680731, -32.957056] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. Nº 609 Floriano Zapata" }, "id": 74904},
       { "geometry": { "type": "Point", "coordinates": [ -60.654565, -32.968155] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Hospitl Vilela" }, "id": 77031},
       { "geometry": { "type": "Point", "coordinates": [ -60.685954, -32.949908] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Asociacion Deportiva  Juan XXIII" }, "id": 77733},
       { "geometry": { "type": "Point", "coordinates": [ -60.67242, -32.961108] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. Nº 93 Guido T Spano" }, "id": 77732},
       { "geometry": { "type": "Point", "coordinates": [ -60.66562, -32.960111] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Patinodromo Municipal" }, "id": 75257},
       { "geometry": { "type": "Point", "coordinates": [ -60.694429, -32.950953] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Centro comunitario Trabajo y Esperanza" }, "id": 77026},
       { "geometry": { "type": "Point", "coordinates": [ -60.688686, -32.946461] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84586},
       { "geometry": { "type": "Point", "coordinates": [ -60.645882, -32.943477] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 120032},
       { "geometry": { "type": "Point", "coordinates": [ -60.670551, -32.939609] },
                "type": "Feature", "properties": { "popupContent": "Mercado del Patio" }, "id": 120036},
       { "geometry": { "type": "Point", "coordinates": [ -60.665644, -32.952586] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 120034},
       { "geometry": { "type": "Point", "coordinates": [ -60.681645, -32.955356] },
                "type": "Feature", "properties": { "popupContent": "Daytona Motopartes" }, "id": 120035},
       { "geometry": { "type": "Point", "coordinates": [ -60.670249, -32.933517] },
                "type": "Feature", "properties": { "popupContent": "Personal Iriondo" }, "id": 123542},
       { "geometry": { "type": "Point", "coordinates": [ -60.656453, -32.92791] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118875},
       { "geometry": { "type": "Point", "coordinates": [ -60.651404, -32.937299] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118897},
       { "geometry": { "type": "Point", "coordinates": [ -60.684733, -32.933849] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 118895},
       { "geometry": { "type": "Point", "coordinates": [ -60.678155, -32.933441] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119137},
       { "geometry": { "type": "Point", "coordinates": [ -60.656353, -32.940648] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119388},
       { "geometry": { "type": "Point", "coordinates": [ -60.657575, -32.935792] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 119141},
       { "geometry": { "type": "Point", "coordinates": [ -60.644611, -32.934939] },
                "type": "Feature", "properties": { "popupContent": "Edificio Pilares del Rio" }, "id": 129252},
       { "geometry": { "type": "Point", "coordinates": [ -60.650901, -32.933079] },
                "type": "Feature", "properties": { "popupContent": "Queens Boulevard" }, "id": 129248},
       { "geometry": { "type": "Point", "coordinates": [ -60.6871, -32.945522] },
                "type": "Feature", "properties": { "popupContent": "Deposito de drogueria" }, "id": 129280},
       { "geometry": { "type": "Point", "coordinates": [ -60.644621, -32.940559] },
                "type": "Feature", "properties": { "popupContent": "Supermercado Coto - sucursal 097 (deposito)" }, "id": 129253},
       { "geometry": { "type": "Point", "coordinates": [ -60.676944, -32.95366] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Esc. Zona Parque" }, "id": 75258},
       { "geometry": { "type": "Point", "coordinates": [ -60.678362, -32.959252] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion:" }, "id": 75611},
       { "geometry": { "type": "Point", "coordinates": [ -60.691228, -32.958274] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: CMD Oeste" }, "id": 75968},
       { "geometry": { "type": "Point", "coordinates": [ -60.677561, -32.954802] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Escuela 119 Cnel. Ortiz de Ocampo" }, "id": 75965},
       { "geometry": { "type": "Point", "coordinates": [ -60.678689, -32.959249] },
                "type": "Feature", "properties": { "popupContent": "Centro de recepcion: Club Atletico Francisco de Godoy" }, "id": 76318},
       { "geometry": { "type": "Point", "coordinates": [ -60.657251, -32.947516] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84600},
       { "geometry": { "type": "Point", "coordinates": [ -60.674207, -32.947161] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84603},
       { "geometry": { "type": "Point", "coordinates": [ -60.676601, -32.951104] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84618},
       { "geometry": { "type": "Point", "coordinates": [ -60.652867, -32.940869] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84623},
       { "geometry": { "type": "Point", "coordinates": [ -60.663045, -32.952266] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84632},
       { "geometry": { "type": "Point", "coordinates": [ -60.652567, -32.953864] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84633},
       { "geometry": { "type": "Point", "coordinates": [ -60.679912, -32.944159] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84636},
       { "geometry": { "type": "Point", "coordinates": [ -60.672721, -32.945454] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84637},
       { "geometry": { "type": "Point", "coordinates": [ -60.694733, -32.943186] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84639},
       { "geometry": { "type": "Point", "coordinates": [ -60.648837, -32.949172] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84648},
       { "geometry": { "type": "Point", "coordinates": [ -60.675146, -32.962145] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84649},
       { "geometry": { "type": "Point", "coordinates": [ -60.687503, -32.932317] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84631},
       { "geometry": { "type": "Point", "coordinates": [ -60.649993, -32.930709] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84621},
       { "geometry": { "type": "Point", "coordinates": [ -60.668541, -32.941579] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84660},
       { "geometry": { "type": "Point", "coordinates": [ -60.668206, -32.941552] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84661},
       { "geometry": { "type": "Point", "coordinates": [ -60.6889, -32.939047] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84670},
       { "geometry": { "type": "Point", "coordinates": [ -60.672781, -32.948464] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Plastico Naranja Superior" }, "id": 84673},
       { "geometry": { "type": "Point", "coordinates": [ -60.658996, -32.931935] },
                "type": "Feature", "properties": { "popupContent": "Edificio Ovidio Lagos" }, "id": 123777},
       { "geometry": { "type": "Point", "coordinates": [ -60.659153, -32.931563] },
                "type": "Feature", "properties": { "popupContent": "Drogueria Nodo Rosario" }, "id": 123778} ] };
