var isla = {
          "type": "FeatureCollection",
          "features": [
       { "geometry": { "type": "Point", "coordinates": [ -60.679383, -32.922661] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120383},
       { "geometry": { "type": "Point", "coordinates": [ -60.688056, -32.876168] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120395},
       { "geometry": { "type": "Point", "coordinates": [ -60.687675, -32.881157] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120399},
       { "geometry": { "type": "Point", "coordinates": [ -60.675799, -32.927157] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120402},
       { "geometry": { "type": "Point", "coordinates": [ -60.687089, -32.887188] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120403},
       { "geometry": { "type": "Point", "coordinates": [ -60.677432, -32.925113] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120407},
       { "geometry": { "type": "Point", "coordinates": [ -60.68345, -32.918325] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120408},
       { "geometry": { "type": "Point", "coordinates": [ -60.684693, -32.91602] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120410},
       { "geometry": { "type": "Point", "coordinates": [ -60.689382, -32.873452] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120412},
       { "geometry": { "type": "Point", "coordinates": [ -60.681881, -32.920282] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120417},
       { "geometry": { "type": "Point", "coordinates": [ -60.699195, -32.904925] },
                "type": "Feature", "properties": { "popupContent": "Contenedor - Metalico Naranja Lateral" }, "id": 120770} ] };
